#!/usr/bin/env Rscript

# Compatibility wrapper.
# The clean Patterns-ready diagnostic snapshot is now generated by
# scripts/33_make_paperx_figures.R as Figure_3_TTEDR_diagnostic_snapshot.pdf.
message("The diagnostic snapshot is generated by scripts/33_make_paperx_figures.R.")
message("Run: Rscript scripts/33_make_paperx_figures.R")
